In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

def find_file(filename):
    candidates = [
        Path(filename),
        Path.cwd() / filename,
        Path("/mnt/data") / filename,
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError(f"Could not find {filename}")


try:
    details_path = find_file("order_details.csv")
except FileNotFoundError:
    details_path = find_file("order_details(3).csv")

df = pd.read_csv(details_path)

print("Dataset shape:", df.shape)
print("Cities:", sorted(df["order_city"].dropna().unique()))

Dataset shape: (151803, 10)
Cities: ['B', 'K', 'U']

In [2]:
city_bikers = (
    df.groupby("order_city")["biker"]
      .nunique()
      .rename("Unique Bikers")
      .reset_index()
      .rename(columns={"order_city": "City"})
      .sort_values("City")
)

display(city_bikers)

  City  Unique Bikers
0    B            478
1    K           2458
2    U           1362

In [3]:
district_vendors = (
    df.groupby(["order_city", "district"])["vendor"]
      .nunique()
      .rename("Unique Vendors")
      .reset_index()
      .rename(columns={
          "order_city": "City",
          "district": "District"
      })
      .sort_values(["City", "District"])
      .reset_index(drop=True)
)

display(district_vendors)

   City  District  Unique Vendors
0     B      3720             110
1     B      3724              39
2     B      3728              39
3     B      3732              15
4     B      3740              73
5     B      3752               5
6     K      1468              48
7     K      1472               1
8     K      1476              49
9     K      1480             299
10    K      1484              69
11    K      1488               1
12    K      1492               3
13    K      1496              19
14    K      1508             117
15    K      1512             124
16    K      1520               7
17    K      1528              95
18    K      4176             124
19    K      4532             110
20    K      4732              55
21    U      1392               1
22    U      1396              75
23    U      1400              27
24    U      1404              64
25    U      1408              30
26    U      1412               5
27    U      1416              65
28    U      1420             156
29    U      1424               9
30    U      1428             109
31    U      1432             188

In [4]:
summary = district_vendors.merge(
    city_bikers.rename(columns={"Unique Bikers": "Unique Bikers in City"}),
    on="City",
    how="left"
)

summary = summary[
    ["City", "District", "Unique Vendors", "Unique Bikers in City"]
]

display(summary)

   City  District  Unique Vendors  Unique Bikers in City
0     B      3720             110                    478
1     B      3724              39                    478
2     B      3728              39                    478
3     B      3732              15                    478
4     B      3740              73                    478
5     B      3752               5                    478
6     K      1468              48                   2458
7     K      1472               1                   2458
8     K      1476              49                   2458
9     K      1480             299                   2458
10    K      1484              69                   2458
11    K      1488               1                   2458
12    K      1492               3                   2458
13    K      1496              19                   2458
14    K      1508             117                   2458
15    K      1512             124                   2458
16    K      1520               7                   2458
17    K      1528              95                   2458
18    K      4176             124                   2458
19    K      4532             110                   2458
20    K      4732              55                   2458
21    U      1392               1                   1362
22    U      1396              75                   1362
23    U      1400              27                   1362
24    U      1404              64                   1362
25    U      1408              30                   1362
26    U      1412               5                   1362
27    U      1416              65                   1362
28    U      1420             156                   1362
29    U      1424               9                   1362
30    U      1428             109                   1362
31    U      1432             188                   1362

In [5]:
overall = pd.DataFrame({
    "Metric": [
        "Unique Cities",
        "Unique Districts",
        "Unique Vendors",
        "Unique Bikers"
    ],
    "Value": [
        df["order_city"].nunique(),
        df["district"].nunique(),
        df["vendor"].nunique(),
        df["biker"].nunique()
    ]
})

display(overall)

             Metric  Value
0     Unique Cities      3
1  Unique Districts     32
2    Unique Vendors   2110
3     Unique Bikers   4298